version: "3"

services:
  geth:
    build: ./geth
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545/udp"
    depends_on:
      - constellation

  bootnode:
    build: ./bootnode
    ports:
      - "33445:33445/udp"
      - "33445:33445"

  constellation:
    build: ./constellation
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "9000:9000"
