version: "2"

services:
  geth-svc:
    build: ./geth
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545"
    depends_on:
      - constellation-svc
      - bootnode-svc

  bootnode-svc:
    build: ./bootnode
    ports:
      - "33445:33445/udp"
      - "33445:33445"

  constellation-svc:
    build: ./constellation
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "9000:9000"

  cakeshops-svc:
    image: jpmc/cakeshop
    environment:
      -  JAVA_OPTS="-Dgeth.url=http\://geth-svc\:8545 -Dgeth.node.port=30301 -Dgeth.node.port=30301 -Dgeth.networkid=${GETH_NETWORK_ID}"
    volumes:
      - ./data:/opt/cakeshop/data
    ports:
      - "8080:8080"
      - "30303:30301"
      - "30303:30301/udp"
    depends_on:
      - geth-svc
    links:
      - geth-svc
