version: "2"

services:
  geth-svc:
    build: ./geth
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545"
    depends_on:
      - constellation-svc

  constellation-svc:
    build: ./constellation
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "9000:9000"
    restart: always