version: "3"

services:
  geth:
    build: ./geth
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545/udp"
    depends_on:
      - constellation

  constellation:
    build: ./constellation
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "9000:9000"
