version: "2"

services:
  geth-svc:
    build: ./geth
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545"
    depends_on:
      - constellation-svc
      - bootnode-svc
    restart: always

  bootnode-svc:
    build: ./bootnode
    ports:
      - "33445:33445/udp"
      - "33445:33445"
    restart: always

  constellation-svc:
    build: ./constellation
    volumes:
      - ./chain:/opt/quorum/data
    ports:
      - "9000:9000"
    restart: always

  cakeshops-svc:
    build: ./cakeshop
    volumes:
      - ./data:/opt/cakeshop/data
    ports:
      - "8080:8080"
      - "30301:30301"
      - "30301:30301/udp"
    depends_on:
      - geth-svc
    links:
      - geth-svc
    restart: always